### ISSUE TITLE
Hacktoberfest

### ISSUE THREAD

**Issue by StanleyMasinde** [stannlee/vue-laravel-spa#6]
I need help finishing this project because I have limited time
Please check the following issues #8 #7

**Comment by cdterry87** [comment]
What kind of features are you hoping to add to the project?

**Comment by StanleyMasinde** [comment]
> What kind of features are you hoping to add to the project?

@cdterry87 

- Authentication and vue router middlewares I know these features are in Laravel But I want them as a single page application

- Async components for the router components so that a user only loads the views he/She visits.

- Any other enhancements you might think of

**Comment by Larsklopstra** [comment]
Could you split each requirement in different issues so multiple people could work on it?

**Comment by StanleyMasinde** [comment]
Let me do that @Larsklopstra
