### ISSUE TITLE
Async component resolution with vue router

### ISSUE THREAD

**Issue by StanleyMasinde** [stannlee/vue-laravel-spa#8]
I want something like the about route instead of compiling all views in one file.
The views are chunked but for some reason, it does not work at all I get a blank page after navigating to any route
![Screenshot from 2019-10-08 09-48-04](https://user-images.githubusercontent.com/35426405/66373275-f676af80-e9b0-11e9-9b29-d95aac6c17df.png)

**Comment by hallowcard13** [comment]
can i handle this ?

**Comment by StanleyMasinde** [comment]
yes @hallowcard13 please do
